### ISSUE TITLE
CCI Data type inconsistency

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/pgstigcheck-inspec#6]
[One of the controls](https://github.com/CrunchyData/pgstigcheck-inspec/blob/master/controls/V-72841.rb#L82) has multiple CCIs (string array), however [every other control](https://github.com/CrunchyData/pgstigcheck-inspec/blob/master/controls/V-72845.rb#L58) is just a single string.  This causes the output json to not be consistent and breaks JSON unmarshallers.

It needs to be an array with a single value on all others or just one CCI as a string in the control that's different.

**Comment by aaronlippold** [comment]
The reason this control has multiple CCI values is because it has more than one NIST 800-53 mapping. This is correct. 

What errors are you seeing, the solution will need to be to update the parsing of the data in the JSON unmarshallers as like it or not this control has more than one CCI. 

Another approach could be to make the single strings arrays to keep the parsing consistent.
